# Generated by Django 4.2.8 on 2023-12-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_comments', '0003_rename_reply_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='reply',
        ),
    ]
