# Generated by Django 4.2.8 on 2023-12-29 08:21

from django.db import migrations, models
import spa_comments.models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_comments', '0004_rename_comment_reply_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='is_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(null=True, upload_to=spa_comments.models.create_path_for_file),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to=spa_comments.models.create_path_for_image),
        ),
    ]
