# Generated by Django 4.2.8 on 2023-12-29 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import spa_comments.models


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments", "0005_rename_reply_comment_is_reply_comment_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_reply",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spa_comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=spa_comments.models.create_path_for_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=spa_comments.models.create_path_for_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "gif", "png"]
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
