# Generated by Django 4.1 on 2023-12-31 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import spa_comments.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spa_comments",
            "0006_remove_comment_is_reply_comment_parent_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=spa_comments.models.create_path_for_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt"]
                    ),
                    spa_comments.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="spa_comments.comment",
            ),
        ),
    ]
