version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata comments_fixture.json &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    env_file:
      - .env

  django-q:
    build: .
    command: python manage.py qcluster
    depends_on:
      - app
      - redis
    env_file:
      - .env
